# This file defines which tasks are used when parsing blocks
# Creating your own execution plan with the tasks you need for your application
# Format follows the TOML format: https://toml.io/en/

# Note: the order you specify tasks in this file matters
#       ex: if task Foo depends on task Bar, place Bar first in the list

# You can find task the task name by looking at the TASK_NAME field inside the task
# Some tasks may allow extra parameters that you can specify in this file

[GenesisBlockTask]
include_payload=false

[GenesisTransactionTask]
include_payload=false

[ByronBlockTask]
readonly=false
include_payload=false

[ByronTransactionTask]
readonly=false
include_payload=false

[ByronAddressTask]

[ByronOutputTask]

[ByronInputTask]

[MultieraBlockTask]
readonly=true
include_payload=false

[MultieraTransactionTask]
readonly=false
include_payload=false

[MultieraMetadataTask]
readonly=false

[MultieraAssetMintTask]
readonly=false

[MultieraCip25EntryTask]
