source:
  type: oura
  socket: "/app/node-ipc/node.socket" # or url
  bearer: Unix # or Tcp

sink:
  type: cardano
  db:
    type: postgres
    database_url: postgresql://carp:carpdb@<postgres host address>:5432/carp
  network: mainnet # preview / preprod / testnet

start_block:
